# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "j6AdN7TVw/mKNYxDXfKeI8vwTGxsia3+HceIbPWZj1OUFf7caDkyyEnYaY6wXeRs9FbhXzzZPZcFQcAfXb1OyVhWJ4Y8x0iM98Z12jqGqL5QVHBqPlJ0U0Y8CYakQhA799UkM48P+x8+/zr6A+446uh/B9A0Unvb0W4VCtOfnw+PZ8AUQIh17w3da9bb1E2GqEZH0ugoAVxKpysnB2tvaAM+CTOy6fMULduaxPdFooj7U3AKlkAvoKtsHn8WeDc5oyogh0itfg1glJnG0Uhu3ndXGoJLw0IQHMDmIMs6XrqIe/ALN3KCySGFgeMb2UqFExkweqC/Bw2fxZQ8uxCdT+jL0c1fcY0w9gDRZ4itRPprqM8/rFR4l10LcrI7XT0JjBHs0vx4NtR/sDVBpb90nQCr0UfPK/ovY4XR1hXBNh1CSHnAoh8sJzKx3St8eK31whNainMW7c1dWQ6ffU+3KxzpNTSJp937/98v7jSEe/IQPSgAL+YgE/hj+emu9C67fR9Pgmj2jeKZIDXRX+9jCQaH9Tg22LaKcfOCGrt1UOH1vbPhIrpOf8zXtbA3HvzcelLoJQuSg9DpEFMHw+seDzUFz6dFDLp89rfRxWfHWofA/C3XRAhM3OWHX2bCYdLJw8qB4KKke6nWbWUNvtkkH+MLYlfU+sVOEopeZwEaVkY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
