travis:
  secure:
    BINSTAR_TOKEN: j6AdN7TVw/mKNYxDXfKeI8vwTGxsia3+HceIbPWZj1OUFf7caDkyyEnYaY6wXeRs9FbhXzzZPZcFQcAfXb1OyVhWJ4Y8x0iM98Z12jqGqL5QVHBqPlJ0U0Y8CYakQhA799UkM48P+x8+/zr6A+446uh/B9A0Unvb0W4VCtOfnw+PZ8AUQIh17w3da9bb1E2GqEZH0ugoAVxKpysnB2tvaAM+CTOy6fMULduaxPdFooj7U3AKlkAvoKtsHn8WeDc5oyogh0itfg1glJnG0Uhu3ndXGoJLw0IQHMDmIMs6XrqIe/ALN3KCySGFgeMb2UqFExkweqC/Bw2fxZQ8uxCdT+jL0c1fcY0w9gDRZ4itRPprqM8/rFR4l10LcrI7XT0JjBHs0vx4NtR/sDVBpb90nQCr0UfPK/ovY4XR1hXBNh1CSHnAoh8sJzKx3St8eK31whNainMW7c1dWQ6ffU+3KxzpNTSJp937/98v7jSEe/IQPSgAL+YgE/hj+emu9C67fR9Pgmj2jeKZIDXRX+9jCQaH9Tg22LaKcfOCGrt1UOH1vbPhIrpOf8zXtbA3HvzcelLoJQuSg9DpEFMHw+seDzUFz6dFDLp89rfRxWfHWofA/C3XRAhM3OWHX2bCYdLJw8qB4KKke6nWbWUNvtkkH+MLYlfU+sVOEopeZwEaVkY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
